fm_elfinder:
    instances:
        default:
            locale: fr
            editor: ckeditor
            theme: smoothness
            #include_assets: true
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads/images
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_max_size: 2M
